[package]
name = "wakalaka-rs"
version = "0.1.1-alpha"
authors = ["Kawaxte"]
edition = "2021"
rust-version = "1.75.0"
readme = "README.md"
description = "No-bullshit general-purpose Discord bot written with love in Rust."
repository = "https://github.com/Kawaxte/wakalaka-rs"
license-file = "LICENSE"
build = "build.rs"
publish = false

[dependencies]
chrono = "0.4.31"
dashmap = "5.5.3"
dirs = "5.0.1"
poise = "0.6.1-rc1"
rand = "0.8.5"
serde = "1.0.193"
serde_json = "1.0.108"
serenity = "0.12.0"
tokio = { version = "1.35.1", features = [
    "macros",
    "rt-multi-thread",
    "io-std",
] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
dotenvy = "0.15.7"
lazy_static = "1.4.0"
sqlx = { version = "0.7.3", features = [
    "migrate",
    "chrono",
    "runtime-tokio",
    "runtime-tokio-rustls",
    "sqlite",
] }
reqwest = { version = "0.11.23", features = ["tokio-native-tls"] }
regex = "1.10.2"
uuid = { version = "1.7.0", features = ["v4"] }
anyhow = "1.0.79"
toml = "0.8.8"
