[package]
name = "wakalaka-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.31"
dirs = "5.0.1"
lazy_static = "1.4.0"
linked-hash-map = { version = "0.5.6", features = ["serde", "serde_impl"] }
png = "0.17.10"
poise = "0.6.1-rc1"
reqwest = "0.11.23"
serde = "1.0.193"
serde_json = "1.0.108"
serenity = { version = "0.12.0", features = ["builder"] }
tokio = { version = "1.35.1", features = ["macros", "rt-multi-thread"] }
toml = { version = "0.8.8", features = ["preserve_order"] }
