# Copyright (C) 2024 Kawaxte
# 
# wakalaka-rs is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# wakalaka-rs is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
# 
# You should have received a copy of the GNU Lesser General Public License
# along with wakalaka-rs. If not, see <http://www.gnu.org/licenses/>.

name: Bug Report
description: |
  Report bug(s) to help us improve yours truly.
title: "[Bug Report]:"
labels: [ bug ]
assignees:
  - Kawaxte
body:
  - type: markdown
    attributes:
      value: |
        Before submitting a bug report, ensure that you have searched for similar reports. There is a chance that somebody else has already reported the same issue.
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: |
        Describe this (or these) bug(s) you have encountered.
      placeholder: |
        I encountered a bug when...
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: |
        Describe steps required to reproduce this (or these) bug(s).
      placeholder: |
        Steps to reproduce this bug are...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: |
        Describe what you expected to happen.
      placeholder: |
        I expected that...
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: |
        Describe what actually happened.
      placeholder: |
        What actually happened was...
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: |
        If applicable, add screenshot(s) to help explain your problem.
    validations:
      required: false
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        Describe environment in which this (or these) bug(s) occurred (e.g., operating system, browser, etc.)
      placeholder: |
        The bug occurred on...
    validations:
      required: true