name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        rust: [stable]

    steps:
    - uses: actions/checkout@v3
    - uses: hecrj/setup-rust-action@v2
      with:
        rust-version: ${{ matrix.rust }}
    - name: Install 'libatk1.0-dev' on Ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get install -y libatk1.0-dev
    - name: Install 'libgtk-3-dev' on Ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get install -y libgtk-3-dev
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose